[package]
name = "cthulhutech"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13.5"
actix-files = "0.6.6"
actix-web = "4.11.0"
actix-web-actors = "4.3.0"
rand = "0.9.2"
serde = "1.0.219"
serde_json = "1.0.141"